/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface StyleMetadataJs {
  language: string
  formality: string
  preferredPhrases: Array<string>
  emotionalTone: EmotionalToneJs
  avoidPatterns: Array<string>
  contextPreferences: string
  timestamp: number
  interactionCount: number
}
export interface EmotionalToneJs {
  warmth: number
  directness: number
}
export interface InteractionContextJs {
  language?: string
  topic?: string
}
export declare function learnPattern(userMessage: string, agentResponse: string, context: InteractionContextJs, existingStyle?: StyleMetadataJs | undefined | null): StyleMetadataJs
export declare function applyStyle(message: string, styleMetadata: StyleMetadataJs): string
export interface DeriveKeyOptions {
  algorithm: string
  memoryCost?: number
  timeCost?: number
  parallelism?: number
}
export interface EncryptResult {
  nonce: Buffer
  ciphertext: Buffer
  authTag: Buffer
}
export declare function deriveKey(passphrase: string, salt: Buffer, options?: DeriveKeyOptions | undefined | null): Promise<Buffer>
export declare function deriveKeySync(passphrase: string, salt: Buffer, options?: DeriveKeyOptions | undefined | null): Buffer
export declare function encrypt(key: Buffer, plaintext: Buffer): EncryptResult
export declare function decrypt(key: Buffer, nonce: Buffer, ciphertext: Buffer, authTag: Buffer): Buffer
export declare function generateSalt(): Buffer
export declare function generateNonce(): Buffer
export declare function noopAsync(): Promise<void>
export declare function noopSync(): void
export declare function copyBuffer(input: Buffer): Buffer
