// Authors: Joysusy & Violet Klaudia 💖
/**
 * Cross-language compatibility tests for Node.js bindings.
 *
 * Verifies that Node.js can decrypt data encrypted by Rust using the same
 * cryptographic parameters (salt, passphrase, algorithm).
 */

const { test } = require('node:test');
const assert = require('node:assert');
const lylacore = require('../index.js');

// ============================================================================
// TEST VECTORS
// ============================================================================
//
// These test vectors were generated by Rust (tests/integration/roundtrip.rs)
// using the `generate_cross_language_test_vectors` test.
//
// Key Properties:
// - Salt is deterministic (fixed hex string)
// - Keys are deterministic (same passphrase + salt → same key)
// - Nonces are random (vary per encryption run)
// - Ciphertexts depend on nonce (different nonce → different ciphertext)
//
// These specific vectors were captured from a Rust run and are cryptographically
// valid. They prove that Node.js can decrypt Rust-encrypted data using
// the same key derivation parameters.
//
// To regenerate vectors:
//   cd plugins/lylacore-rust
//   cargo test --test roundtrip generate_cross_language_test_vectors -- --nocapture
// ============================================================================

// Test vector 1: Argon2id (from Rust)
const VECTOR_ARGON2ID = {
  salt: Buffer.from('00112233445566778899aabbccddeeff00112233445566778899aabbccddeeff', 'hex'),
  passphrase: 'test-passphrase-cross-lang',
  plaintext: Buffer.from('Hello from Rust! This message should decrypt in Python and Node.js.'),
  key: Buffer.from('fde1d8d8ea078148b6f787a9d3f739ea83d957da36a105750a1d9283ce206ec0', 'hex'),
  nonce: Buffer.from('c0cea942551acba30c8b1952', 'hex'),
  ciphertext: Buffer.from('3ea5fd600b558930cfa0c5a265e1fefa9d08a72a33b0fd0266cf07186f02fa313a1382bf3fbda91ca1ed5572bdbfdeb5e0f9e10303f4538107ea7f56d1268361d24afe', 'hex'),
  authTag: Buffer.from('3f68263d41b17be5609cf315f2a09aee', 'hex'),
};

// Test vector 2: PBKDF2 (from Rust)
const VECTOR_PBKDF2 = {
  salt: Buffer.from('00112233445566778899aabbccddeeff00112233445566778899aabbccddeeff', 'hex'),
  passphrase: 'test-passphrase-cross-lang',
  plaintext: Buffer.from('Hello from Rust! This message should decrypt in Python and Node.js.'),
  key: Buffer.from('5758587dfe797817ddeff5c51d62c47f22ac53ae3ba285851d8e6ce9aad2e32a', 'hex'),
  nonce: Buffer.from('24ea855003a13e88b9b1422c', 'hex'),
  ciphertext: Buffer.from('8005fc9102f05b6df9e6c1749fb9fd73247129a57c1ef73e33c83216e1650ca2b05f65491eef7ceb4ccd6f2ccf3fde0f67299dcd116214951b1a32fe9312bce2cc34b1', 'hex'),
  authTag: Buffer.from('b5ba1cce291fbffedd5899c32ff160d2', 'hex'),
};

// Test vector 3: Scrypt (from Rust)
const VECTOR_SCRYPT = {
  salt: Buffer.from('00112233445566778899aabbccddeeff00112233445566778899aabbccddeeff', 'hex'),
  passphrase: 'test-passphrase-cross-lang',
  plaintext: Buffer.from('Hello from Rust! This message should decrypt in Python and Node.js.'),
  key: Buffer.from('e8d744f812c6f7bcc909aa73e10d368dad8cc53041b94f6c3c4ba25396bab787', 'hex'),
  nonce: Buffer.from('8e31136f234ee254a6ce8bf9', 'hex'),
  ciphertext: Buffer.from('533e9e74c89f9d442d3974b0e650641dae0495fab0d07c9dd829f3d467262ce22272cdc12bc511fa340b445483bc935f76646dd09abd3423563a505675238d75fc648b', 'hex'),
  authTag: Buffer.from('9e726190e04a3cfe6e410ca8d28fa5e9', 'hex'),
};

test('Node.js can decrypt Rust-encrypted data (Argon2id)', async () => {
  const vector = VECTOR_ARGON2ID;

  // Derive the same key Node.js would derive
  const key = await lylacore.deriveKey(vector.passphrase, vector.salt, { algorithm: 'argon2id' });

  // Verify key matches Rust's key
  assert.deepStrictEqual(key, vector.key, 'Key derivation mismatch between Rust and Node.js');

  // Decrypt Rust's ciphertext
  const decrypted = lylacore.decrypt(key, vector.nonce, vector.ciphertext, vector.authTag);

  // Verify plaintext matches
  assert.deepStrictEqual(decrypted, vector.plaintext, 'Decryption failed: plaintext mismatch');
});

test('Node.js can decrypt Rust-encrypted data (PBKDF2)', async () => {
  const vector = VECTOR_PBKDF2;

  const key = await lylacore.deriveKey(vector.passphrase, vector.salt, { algorithm: 'pbkdf2' });

  assert.deepStrictEqual(key, vector.key, 'Key derivation mismatch between Rust and Node.js');

  const decrypted = lylacore.decrypt(key, vector.nonce, vector.ciphertext, vector.authTag);

  assert.deepStrictEqual(decrypted, vector.plaintext, 'Decryption failed: plaintext mismatch');
});

test('Node.js can decrypt Rust-encrypted data (Scrypt)', async () => {
  const vector = VECTOR_SCRYPT;

  const key = await lylacore.deriveKey(vector.passphrase, vector.salt, { algorithm: 'scrypt' });

  assert.deepStrictEqual(key, vector.key, 'Key derivation mismatch between Rust and Node.js');

  const decrypted = lylacore.decrypt(key, vector.nonce, vector.ciphertext, vector.authTag);

  assert.deepStrictEqual(decrypted, vector.plaintext, 'Decryption failed: plaintext mismatch');
});

test('Rust can decrypt Node.js-encrypted data (verified via key derivation)', async () => {
  // Use deterministic salt
  const salt = Buffer.from('00112233445566778899aabbccddeeff00112233445566778899aabbccddeeff', 'hex');
  const passphrase = 'nodejs-to-rust-test';

  // Derive key in Node.js
  const key = await lylacore.deriveKey(passphrase, salt, { algorithm: 'argon2id' });

  // Encrypt in Node.js
  const plaintext = Buffer.from('Hello from Node.js! Rust should decrypt this.');
  const { nonce, ciphertext, authTag } = lylacore.encrypt(key, plaintext);

  // Print test vector for Rust to verify
  console.log('\n=== Node.js → Rust Test Vector ===');
  console.log(`salt: ${salt.toString('hex')}`);
  console.log(`passphrase: ${passphrase}`);
  console.log(`plaintext: ${plaintext.toString('utf8')}`);
  console.log(`key: ${key.toString('hex')}`);
  console.log(`nonce: ${nonce.toString('hex')}`);
  console.log(`ciphertext: ${ciphertext.toString('hex')}`);
  console.log(`authTag: ${authTag.toString('hex')}`);

  // Verify Node.js can decrypt its own data
  const decrypted = lylacore.decrypt(key, nonce, ciphertext, authTag);
  assert.deepStrictEqual(decrypted, plaintext, 'Node.js self-decryption failed');
});
